package com.dandelion.memberandroid.dao.auto;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACCOUNT.
 */
public class Account {

    private Long id;
    /** Not-null value. */
    private String sid;
    private long skey;
    private long usdId;
    private int accountType;
    /** Not-null value. */
    private java.util.Date createdDate;
    /** Not-null value. */
    private java.util.Date modifyDate;

    public Account() {
    }

    public Account(Long id) {
        this.id = id;
    }

    public Account(Long id, String sid, long skey, long usdId, int accountType, java.util.Date createdDate, java.util.Date modifyDate) {
        this.id = id;
        this.sid = sid;
        this.skey = skey;
        this.usdId = usdId;
        this.accountType = accountType;
        this.createdDate = createdDate;
        this.modifyDate = modifyDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSid() {
        return sid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSid(String sid) {
        this.sid = sid;
    }

    public long getSkey() {
        return skey;
    }

    public void setSkey(long skey) {
        this.skey = skey;
    }

    public long getUsdId() {
        return usdId;
    }

    public void setUsdId(long usdId) {
        this.usdId = usdId;
    }

    public int getAccountType() {
        return accountType;
    }

    public void setAccountType(int accountType) {
        this.accountType = accountType;
    }

    /** Not-null value. */
    public java.util.Date getCreatedDate() {
        return createdDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedDate(java.util.Date createdDate) {
        this.createdDate = createdDate;
    }

    /** Not-null value. */
    public java.util.Date getModifyDate() {
        return modifyDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModifyDate(java.util.Date modifyDate) {
        this.modifyDate = modifyDate;
    }

}
