package com.dandelion.memberandroid.dao.auto;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dandelion.memberandroid.dao.auto.Account;
import com.dandelion.memberandroid.dao.auto.MemberInfo;
import com.dandelion.memberandroid.dao.auto.MerchantInfo;

import com.dandelion.memberandroid.dao.auto.AccountDao;
import com.dandelion.memberandroid.dao.auto.MemberInfoDao;
import com.dandelion.memberandroid.dao.auto.MerchantInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig memberInfoDaoConfig;
    private final DaoConfig merchantInfoDaoConfig;

    private final AccountDao accountDao;
    private final MemberInfoDao memberInfoDao;
    private final MerchantInfoDao merchantInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        memberInfoDaoConfig = daoConfigMap.get(MemberInfoDao.class).clone();
        memberInfoDaoConfig.initIdentityScope(type);

        merchantInfoDaoConfig = daoConfigMap.get(MerchantInfoDao.class).clone();
        merchantInfoDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        memberInfoDao = new MemberInfoDao(memberInfoDaoConfig, this);
        merchantInfoDao = new MerchantInfoDao(merchantInfoDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(MemberInfo.class, memberInfoDao);
        registerDao(MerchantInfo.class, merchantInfoDao);
    }
    
    public void clear() {
        accountDaoConfig.getIdentityScope().clear();
        memberInfoDaoConfig.getIdentityScope().clear();
        merchantInfoDaoConfig.getIdentityScope().clear();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public MemberInfoDao getMemberInfoDao() {
        return memberInfoDao;
    }

    public MerchantInfoDao getMerchantInfoDao() {
        return merchantInfoDao;
    }

}
