package com.dandelion.memberandroid.dao.auto;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEMBER_INFO.
 */
public class MemberInfo {

    private Long id;
    private String avatarurl;
    private String backgroundurl;
    /** Not-null value. */
    private String name;
    private String address;
    private String phone;
    private String introduction;
    private java.util.Date birthday;
    /** Not-null value. */
    private java.util.Date createddate;
    /** Not-null value. */
    private java.util.Date modifieddate;
    private Integer sex;
    private Long userId;

    public MemberInfo() {
    }

    public MemberInfo(Long id) {
        this.id = id;
    }

    public MemberInfo(Long id, String avatarurl, String backgroundurl, String name, String address, String phone, String introduction, java.util.Date birthday, java.util.Date createddate, java.util.Date modifieddate, Integer sex, Long userId) {
        this.id = id;
        this.avatarurl = avatarurl;
        this.backgroundurl = backgroundurl;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.introduction = introduction;
        this.birthday = birthday;
        this.createddate = createddate;
        this.modifieddate = modifieddate;
        this.sex = sex;
        this.userId = userId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAvatarurl() {
        return avatarurl;
    }

    public void setAvatarurl(String avatarurl) {
        this.avatarurl = avatarurl;
    }

    public String getBackgroundurl() {
        return backgroundurl;
    }

    public void setBackgroundurl(String backgroundurl) {
        this.backgroundurl = backgroundurl;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public java.util.Date getBirthday() {
        return birthday;
    }

    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }

    /** Not-null value. */
    public java.util.Date getCreateddate() {
        return createddate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreateddate(java.util.Date createddate) {
        this.createddate = createddate;
    }

    /** Not-null value. */
    public java.util.Date getModifieddate() {
        return modifieddate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModifieddate(java.util.Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

}
